[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vending-machine"
version = "0.1.0"
description = "Simple vending machine"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/bobamachine"]
